### ISSUE TITLE
Sugerencia para combobar

### ISSUE THREAD

**Issue by pokeinalover** [contratop/PowerLibrary#3]
$destinos = @("des1","des2","des3")

Show-CombobarTextDialog -Title "title" -message "mensaje" -combobar $destinos -buttonlabel "envia c:"

**Comment by contratop** [comment]
falta añadir combobox con texto de entrada para por ejemplo

Telegram: combobox de destinos y texto de enviar mensaje, boton enviar mensaje

**Comment by contratop** [comment]
Agregada dos funciones de combobar
